#!/usr/bin/env bash
set -eo pipefail

export VPC_ROOT=${VPC_ROOT:="/var/lib/vpc"}

function additem()
{
  item=$1
  file=$2
  touch $VPC_ROOT/$file
  if [ ! -z $item ]; then
    if grep -Fxq "$item" $VPC_ROOT/$file
    then
      echo $item
    else
      echo $item >> $VPC_ROOT/$file
      echo $item
    fi
  fi
}

function removeitem()
{
  item=$1
  file=$2
  if [ ! -z $item ]; then
    if grep -Fxq "$item" $VPC_ROOT/$file
    then
      sed -i /$item/d $VPC_ROOT/$file
    fi
  fi
}

function listitems()
{
  file=$1
  touch $VPC_ROOT/$file
  cat $VPC_ROOT/$file
}

function create_services()
{
  withdb=$1
  cat<<EOF > $VPC_ROOT/_ports
22/tcp
22/udp
80/tcp
443/tcp
443/udp
EOF

  if [ ! -z $withdb ]; then
    while read port
    do
      echo "$port/tcp" >> $VPC_ROOT/_ports
      echo "$port/udp" >> $VPC_ROOT/_ports
    done < $VPC_ROOT/ports
  fi

  mv $VPC_ROOT/_ports /etc/firewall/services.conf
}

function create_hosts()
{
  withdb=$1

  if [ ! -z $withdb ]; then
    cp -f $VPC_ROOT/hosts /etc/firewall/ip-whitelist.conf
  else
    echo "" > /etc/firewall/ip-whitelist.conf
  fi
}

case "$1" in

  add-host)
    additem $2 hosts
    ;;

  remove-host)
    removeitem $2 hosts
    ;;

  hosts)
    listitems hosts
    ;;

  add-port)
    case "$2" in
      22)
        echo "standard port";
        ;;
      80)
        echo "standard port";
        ;;
      443)
        echo "standard port";
        ;;
      *)
        additem $2 ports
        ;;
    esac
    ;;

  remove-port)
    removeitem $2 ports
    ;;

  ports)
    listitems ports
    ;;

  ls)
    echo "[hosts]"
    vpc hosts
    echo "[ports]"
    vpc ports
    ;;

  reset)
    rm -f $VPC_ROOT/hosts
    rm -f $VPC_ROOT/ports
    vpc cancel
    ;;

  status)
    /etc/init.d/firewall status
    ;;

  cancel)
    create_services
    create_hosts
    /etc/init.d/firewall restart
    /etc/init.d/firewall status
    ;;

  apply)
    create_services 1
    create_hosts 1
    /etc/init.d/firewall restart
    /etc/init.d/firewall status
    ;;
    
  help)
    echo
    cat<<EOF | sort
    help                                         Print the list of commands
    add-host <ip>                                Expose service ports onto 127.0.0.1
    remove-host <ip>                             Expose service ports onto 127.0.0.1
    hosts                                        List the current hosts
    add-port <port>                              Expose service ports onto 127.0.0.1
    remove-port <port>                           Expose service ports onto 127.0.0.1
    ports                                        List the current ports
    ls                                           Show the current firewall rules
    apply                                        Apply the firewall rules
    cancel                                       Remove the firewall rules
    reset                                        Delete the firewall rules
    status                                       Show the iptables status
EOF
    echo
    ;;

  *)
    vpc help
    ;;

esac